### ISSUE TITLE
Possibility of increasing the number of tuners?

### ISSUE THREAD

**Issue by nix3ss** [duncanleo/plex-dvr-hls#28]
Hello, good job. I just tested it on my windows 11 system and in Plex it appears with 3 tuners available, any possibility to increase that number for example to 8?

I have in the same folder:
- templates folder, with xmltv.tmpl
- channels.json
- config.json
- plex-dvr-hls-windows-amd64.exe

Thank you!!

**Comment by duncanleo** [comment]
hi @nix3ss, this is certainly possible! could you elaborate on what increasing this number would do? I think 3 was just some arbitrary number I set earlier on.

**Comment by nix3ss** [comment]
GOOGLE TRANSLATOR:

Large family. Even if we are watching the same channel, Plex occupies all the tuners, also limiting it to 3 devices. When we are more or less together fine, but sometimes not.

Thank you

**Comment by duncanleo** [comment]
@nix3ss oh that makes sense! I'll add an option to configure it.

**Comment by duncanleo** [comment]
This is now available in [v1.2.5](https://github.com/duncanleo/plex-dvr-hls/releases/tag/v1.2.5), you can check out the example in `config.example.json` to set this option.
